name: Teste de carga Python e K6

on:
  push:
    branches:
      - main  # Substitua 'main' pelo nome da sua branch principal, se necessário

jobs:
  build:
    name: Teste de carga Python e K6
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Especifique a versão do Python que você precisa

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.0'

      - name: Instalar dependências Python
        run: pip install -r requirements.txt

      - name: Install k6
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          sudo apt-add-repository "deb https://dl.k6.io/deb stable main"
          sudo apt-get update
          sudo apt-get install k6

      - name: Executar teste de carga K6 e gerar relatório JSON
        run: k6 run --out json=result.json teste-esteira.js  # Gera um relatório JSON

      - name: Criar diretório de relatório
        run: mkdir -p report

      - name: Criar arquivo k6-reporter.js
        run: |
          echo "const fs = require('fs');

// Carrega o relatório JSON gerado pelo k6
const reportData = JSON.parse(fs.readFileSync('result.json', 'utf8'));

// Gera o conteúdo HTML do relatório
const htmlContent = \`
<!DOCTYPE html>
<html>
<head>
  <title>Relatório de Teste de Carga</title>
</head>
<body>
  <h1>Relatório de Teste de Carga</h1>
  <h2>Resumo</h2>
  <p>Total de requests: \${reportData.metrics.http_reqs.count}</p>
  <p>Duração total: \${reportData.metrics.iterations.duration}</p>
  <!-- Adicione mais métricas conforme necessário -->
</body>
</html>
\`;

// Escreve o conteúdo HTML no arquivo index.html
fs.writeFileSync('report/index.html', htmlContent);" > k6-reporter.js

      - name: Gerar relatório HTML
        run: node k6-reporter.js
        working-directory: ${{ github.workspace }}

      - name: Upload artefato
        uses: actions/upload-artifact@v3
        with: 
          name: Relatório de Teste de Performance
          path: report
